services:
  serveraccesshub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serveraccesshub
    
    env_file:
      - .env

    ports:
      - "8080:8080"
    volumes:
      - ./cloudStorage:/app/cloudStorage
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    environment:
      - LANG=en_US.UTF-8
      - TERM=xterm-256color
      - TZ=Europe/Warsaw
    
    restart: unless-stopped

